version: '3.9'

services:
  nextapp:
    container_name: nextapp
    image: touhousoft/scap-proyect
    build: .
    ports: 
      - "3000:3000"
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=my-secret-pwd
      - DB_NAME=rent_flow_db

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pwd
      - MYSQL_DATABASE=rent_flow_db
